### PR TITLE
Update AutoHeal.java

### PR DESCRIPTION
**Pull request by qloha**
Add golden apple option

## Summary by CodeRabbit

- **New Features**
	- Expanded healing options in the AutoHeal module to include "Golden apple" for automatic use during gameplay.
	- Improved functionality to enhance gameplay strategy and user experience with a wider range of healing items.

### CODE REVIEW

**Comment by qloha** [comment]
https://www.youtube.com/watch?v=OjNpRbNdR7E&t=1s

**Review by xia-mc — CHANGES_REQUESTED** [review]
1. ****Don't**** merge into master branch.
2. do you test it? I think it won't work because eating need more time than using golden head or soup.

**Comment by TejasLamba2006** [comment]
Please test builds and avoid making pull requests without verification, there are syntax errors and as a result this can't be merged.


The second reason for denying this is the dev branch needs to be edited instead of master.


I request @xia-mc to mention this pull request and add the commit manually.

Thanks for the contribution.

**Comment by xia-mc** [comment]
> Please test builds and avoid making pull requests without verification, there are syntax errors and as a result this can't be merged.
> 
> The second reason for denying this is the dev branch needs to be edited instead of master.
> 
> I request @xia-mc to mention this pull request and add the commit manually.
> 
> Thanks for the contribution.

i'm not sure will it work.. you see, eating gapple need more time to do

**Comment by qloha** [comment]
please close this pull request, it was me being dumb ;D

**Pull request closed without merging**
