### PR TITLE
change the drawing of the HealthBar to the gradient color obtained by Theme.getGradients(), consistent with b4

### PR DESCRIPTION
**Pull request by KgDW**
## Summary by CodeRabbit

- **New Features**
	- Introduced a customizable health color setting for the HUD, allowing users to toggle the health bar display on or off based on health status.

- **Improvements**
	- Enhanced health bar rendering logic for clarity and efficiency, ensuring dynamic color adjustments based on the health value.
	- Streamlined drawing process for the health bar and associated text, improving visual feedback and user experience.
	- Refined visual representation of health bars using rounded gradient rectangles for better aesthetics.

### CODE REVIEW

**Comment by TejasLamba2006** [comment]
Hi @KgDW,

Thank you for your contribution! To better understand the context of what you’ve created, could you please provide a screenshot of it? This will help us review your work more effectively.

Looking forward to your response!

**Comment by KgDW** [comment]
before
4A5E11298C552C63834F1E473DE1B6AC
after
D2BFE2D17E128B2F4B3FFB4A9F5E878A

**Comment by KgDW** [comment]
I will fix the issue with health points not having color later

**Comment by KgDW** [comment]
fixed

**Review by xia-mc — APPROVED** [review]
Great.

**Pull request merged**
