### PR TITLE
Add Xray Cave Only Mode

### PR DESCRIPTION
**Pull request by L1shed**
Cave Only Mode is an Xray option that, when enabled, renders only blocks next to at least 1 air block.
The aim is to avoid rendering the blocks artificially sent to the client by the Anti-Xray plugin.

I tested it and it works perfectly.
Note that it may affect performances if the range/rate settings are increased

No reference

By the way i didn't see any contributing guidelines

## Summary by CodeRabbit

- **New Features**
	- Updated to version 1.19-dev, indicating new enhancements and features.
	- Introduced improved error handling in key methods for better stability.
	- Added a new `Notification` class for better organization of notification data.
	- Introduced a `caveOnly` toggle feature for enhanced cave detection during block breaking.
	- Enhanced `Scaffold` class with new settings for improved user control over gameplay.

- **Bug Fixes**
	- Improved accuracy of key state detection logic.

- **Style**
	- Enhanced readability for timer speed output.

- **Documentation**
	- Versioning information updated to reflect changes and development progression.

### CODE REVIEW

**Comment by L1shed** [comment]
Idk why there is all these commits i pushed only one

**Comment by fortXIV** [comment]
i love you

**Review by xia-mc — CHANGES_REQUESTED** [review]
Please **sync the latest branch** before make the pull request.

**Comment by xia-mc** [comment]
> By the way i didn't see any contributing guidelines

Yes, we need a guidelines.

**Pull request closed without merging**
