### PR TITLE
categorize ModuleManager and add ScreenshotHelper

### PR DESCRIPTION
**Pull request by KgDW**
## Summary by CodeRabbit

- **New Features**
  - Introduced multiple new modules across various categories, including Command Chat, Command Line, Gui, Settings, AimAssist, Block Hit, Burst Clicker, Click Assist, Criticals, Tower, and Water Bucket.
  - Added automatic screenshot functionality that triggers based on specific chat messages indicating a win, with configurable delay settings.

- **Improvements**
  - Updated the `AutoPlay` module to include a new Duel Win Message and changed the delay setting to be in seconds for better user configuration.

### CODE REVIEW

**Comment by KgDW** [comment]
btw ScreenshotHelper delayValue 1s is best i think.

**Comment by xia-mc** [comment]
sry for the feature freeze, I have to release a version this night.

**Comment by TejasLamba2006** [comment]
Hello @KgDW, from next time please ensure your merging to `dev` branch

**Comment by KgDW** [comment]
ok

**Pull request closed without merging**
